#
# See https://kubernetes.io/docs/concepts/storage/persistent-volumes/
#
# A walk through of persistent volumes is at https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redis-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
