apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: court
spec:
  selector:
    matchLabels:
      app: court
  serviceName: "court"
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: court # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: court
          image: adarshzededa/pressandplay-court:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50000
              name: http
            - containerPort: 50001
              name: grpc
          env:
            - name: GRPC_EVENT_CLIENT_HOST
              value: "event"
            - name: GRPC_EVENT_CLIENT_PORT
              value: "50001"
            - name: GRPC_USER_CLIENT_HOST
              value: "user"
            - name: GRPC_USER_CLIENT_PORT
              value: "50001"
            - name: GRPC_SERVER_PORT
              value: "50001"
            - name: HTTP_SERVER_HOST
              value: "0.0.0.0"
            - name: HTTP_SERVER_PORT
              value: "50000"
            - name: GCP_PRIVATE_KEY_PATH
              value: "resources/private-key.pem"
            - name: GCP_BUCKET_NAME
              value: "pressandplay"
            - name: GCP_ACCESS_ID
              value: "cloud-storage-object-sa@final-dsc-project.iam.gserviceaccount.com"
            - name: GCP_IMAGE_URL_TEMPLATE
              value: "https://storage.cloud.google.com/pressandplay/%s?authuser=6"
            - name: GCP_CREDENTIALS_PATH
              value: "resources/credentials.json"
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: "admin"
            - name: MONGO_PASSWORD
              value: "admin"
            - name: MONGO_DB
              value: "pressandplay"
            - name: KAFKA_HOST
              value: "kafka-service"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_COURT_DELETE_TOPIC
              value: "court-deleted"
            - name: KAFKA_SLOT_BOOKED_TOPIC
              value: "slot-booked"
            - name: KAFKA_RETRY
              value: "5"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "admin"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_DATA_EXPIRATION_IN_HRS
              value: "5"