apiVersion: v1
kind: Service
metadata:
  name: events
  labels:
    app: events
spec:
  ports:
    - port: 50000
      protocol: TCP
      name: http
      targetPort: 50000
    - port: 50001
      protocol: TCP
      name: grpc
      targetPort: 50001
  selector:
    app: events